power<-read.table("./household_power_consumption.txt", sep=";", skip=66637, nrows=2880)
headings<-read.table("./household_power_consumption.txt", sep=";", nrows=1, header=T)
colnames(power)<-colnames(headings)
power$Date<-as.Date(power$Date, format = "%d/%m/%Y")
DT<-paste(power$Date,power$Time)
DT<-as.POSIXct(DT)
power<-cbind(power,DT)
png(file="plot2.png")
with(power,plot(DT,Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)"))
dev.off()