power<-read.table("./household_power_consumption.txt", sep=";", skip=66637, nrows=2880)
headings<-read.table("./household_power_consumption.txt", sep=";", nrows=1, header=T)
colnames(power)<-colnames(headings)
power$Date<-as.Date(power$Date, format = "%d/%m/%Y")
DT<-paste(power$Date,power$Time)
DT<-as.POSIXct(DT)
power<-cbind(power,DT)
png(file="plot4.png")
par(mfrow = c(2,2))
with(power,plot(DT,Global_active_power, type="l", xlab="", ylab="Global Active Power"))
with(power,plot(DT,Voltage, type="l", xlab="datetime", ylab="Voltage"))
with(power,plot(DT,Sub_metering_1, type="l", xlab="", ylab="Energy sub metering"))
lines(DT,power$Sub_metering_2,type="l",col="Red")
lines(DT,power$Sub_metering_3,type="l",col="Blue")
legend("topright",lty=1,bty="n",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(power,plot(DT,Global_reactive_power, type="l", xlab="datetime"))
dev.off()