power<-read.table("./household_power_consumption.txt", sep=";", skip=66637, nrows=2880)
headings<-read.table("./household_power_consumption.txt", sep=";", nrows=1, header=T)
colnames(power)<-colnames(headings)
png(file="plot1.png")
hist(power$Global_active_power,main="Global Active Power",xlab="Global Active Power (kilowatts)",col="Red")
dev.off()